# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'sound-send' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sound-send
  pod 'Nocilla'

  target 'sound-sendTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nocilla'
  end
  
  target 'sound-sendUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nocilla'
  end

end
